# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-25 11:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('device', '0001_initial'),
        ('controller', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemperatureSensor',
            fields=[
                ('sensor_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='device.Sensor')),
                ('uri', models.CharField(help_text='A device URI such as onewire://182377282', max_length=255)),
                ('slot', models.PositiveIntegerField(blank=True, help_text='The slot ID assigned paired with the Controller', null=True)),
                ('value', models.FloatField(null=True)),
                ('controller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temperaturesensor', to='controller.Controller')),
            ],
            options={
                'abstract': False,
            },
            bases=('device.sensor', models.Model),
        ),
    ]
