# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-31 18:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('device', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DS2413Actuator',
            fields=[
                ('actuator_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='device.Actuator')),
                ('pio', models.PositiveIntegerField(choices=[(0, 'A'), (1, 'B')], default=0, help_text='PIO number of the addressable switch')),
                ('inverted', models.BooleanField(default=False, help_text='If the switch is inverted')),
            ],
            options={
                'verbose_name': 'DS2413',
                'verbose_name_plural': 'DS2413',
            },
            bases=('device.actuator',),
        ),
        migrations.CreateModel(
            name='ManualValve',
            fields=[
                ('manualactuator_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='device.ManualActuator')),
            ],
            options={
                'abstract': False,
            },
            bases=('device.manualactuator', models.Model),
        ),
        migrations.CreateModel(
            name='MotorizedValve',
            fields=[
                ('actuator_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='device.Actuator')),
            ],
            options={
                'abstract': False,
            },
            bases=('device.actuator', models.Model),
        ),
    ]
