# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-25 11:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('device', '0001_initial'),
        ('controller', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DS2413Actuator',
            fields=[
                ('actuator_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='device.Actuator')),
                ('uri', models.CharField(help_text='A device URI such as onewire://182377282', max_length=255)),
                ('slot', models.PositiveIntegerField(blank=True, help_text='The slot ID assigned paired with the Controller', null=True)),
                ('pio', models.PositiveIntegerField(choices=[(0, 'A'), (1, 'B')], default=0, help_text='PIO number of the addressable switch')),
                ('inverted', models.BooleanField(default=False, help_text='If the switch is inverted')),
                ('controller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ds2413actuator', to='controller.Controller')),
            ],
            options={
                'verbose_name_plural': 'DS2413',
                'verbose_name': 'DS2413',
            },
            bases=('device.actuator', models.Model),
        ),
        migrations.CreateModel(
            name='Valve',
            fields=[
                ('actuator_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='device.Actuator')),
            ],
            options={
                'abstract': False,
            },
            bases=('device.actuator',),
        ),
        migrations.CreateModel(
            name='ManualValve',
            fields=[
                ('valve_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core_actuator.Valve')),
            ],
            options={
                'abstract': False,
            },
            bases=('core_actuator.valve',),
        ),
        migrations.CreateModel(
            name='MotorizedValve',
            fields=[
                ('valve_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core_actuator.Valve')),
                ('uri', models.CharField(help_text='A device URI such as onewire://182377282', max_length=255)),
                ('slot', models.PositiveIntegerField(blank=True, help_text='The slot ID assigned paired with the Controller', null=True)),
                ('controller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='motorizedvalve', to='controller.Controller')),
            ],
            options={
                'abstract': False,
            },
            bases=('core_actuator.valve', models.Model),
        ),
    ]
